ServerEvents.recipes(event=>{
    const {mechanical_crafting} = event.recipes.create
    function singularity(singularity, item){
        let id = singularity.split(':')[1]
        mechanical_crafting(singularity,['a'],{a:item.weakNBT()}).id(`singularity:mechanical_crafting/${id}`)
    }

    //魔力奇点
    singularity('kubejs:singularity_mana',Item.of('minecraft:light_blue_shulker_box', '{BlockEntityTag:{Items:[{Count:1b,Slot:0b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:1b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:2b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:3b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:4b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:5b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:6b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:7b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:8b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:9b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:10b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:11b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:12b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:13b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:14b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:15b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:16b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:17b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:18b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:19b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:20b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:21b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:22b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:23b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:24b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:25b,id:"botania:mana_tablet",tag:{mana:500000}},{Count:1b,Slot:26b,id:"botania:mana_tablet",tag:{mana:500000}}],id:"minecraft:shulker_box"}}'))

    //铁
    singularity('kubejs:singularity_iron',Item.of('minecraft:white_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:iron_ingot"},{Count:64b,Slot:1b,id:"minecraft:iron_ingot"},{Count:64b,Slot:2b,id:"minecraft:iron_ingot"},{Count:64b,Slot:3b,id:"minecraft:iron_ingot"},{Count:64b,Slot:4b,id:"minecraft:iron_ingot"},{Count:64b,Slot:5b,id:"minecraft:iron_ingot"},{Count:64b,Slot:6b,id:"minecraft:iron_ingot"},{Count:64b,Slot:7b,id:"minecraft:iron_ingot"},{Count:64b,Slot:8b,id:"minecraft:iron_ingot"},{Count:64b,Slot:9b,id:"minecraft:iron_ingot"},{Count:64b,Slot:10b,id:"minecraft:iron_ingot"},{Count:64b,Slot:11b,id:"minecraft:iron_ingot"},{Count:64b,Slot:12b,id:"minecraft:iron_ingot"},{Count:64b,Slot:13b,id:"minecraft:iron_ingot"},{Count:64b,Slot:14b,id:"minecraft:iron_ingot"},{Count:64b,Slot:15b,id:"minecraft:iron_ingot"},{Count:64b,Slot:16b,id:"minecraft:iron_ingot"},{Count:64b,Slot:17b,id:"minecraft:iron_ingot"},{Count:64b,Slot:18b,id:"minecraft:iron_ingot"},{Count:64b,Slot:19b,id:"minecraft:iron_ingot"},{Count:64b,Slot:20b,id:"minecraft:iron_ingot"},{Count:64b,Slot:21b,id:"minecraft:iron_ingot"},{Count:64b,Slot:22b,id:"minecraft:iron_ingot"},{Count:64b,Slot:23b,id:"minecraft:iron_ingot"},{Count:64b,Slot:24b,id:"minecraft:iron_ingot"},{Count:64b,Slot:25b,id:"minecraft:iron_ingot"},{Count:64b,Slot:26b,id:"minecraft:iron_ingot"}],id:"minecraft:shulker_box"}}'))

    //铜
    singularity('kubejs:singularity_copper',Item.of('minecraft:orange_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:copper_ingot"},{Count:64b,Slot:1b,id:"minecraft:copper_ingot"},{Count:64b,Slot:2b,id:"minecraft:copper_ingot"},{Count:64b,Slot:3b,id:"minecraft:copper_ingot"},{Count:64b,Slot:4b,id:"minecraft:copper_ingot"},{Count:64b,Slot:5b,id:"minecraft:copper_ingot"},{Count:64b,Slot:6b,id:"minecraft:copper_ingot"},{Count:64b,Slot:7b,id:"minecraft:copper_ingot"},{Count:64b,Slot:8b,id:"minecraft:copper_ingot"},{Count:64b,Slot:9b,id:"minecraft:copper_ingot"},{Count:64b,Slot:10b,id:"minecraft:copper_ingot"},{Count:64b,Slot:11b,id:"minecraft:copper_ingot"},{Count:64b,Slot:12b,id:"minecraft:copper_ingot"},{Count:64b,Slot:13b,id:"minecraft:copper_ingot"},{Count:64b,Slot:14b,id:"minecraft:copper_ingot"},{Count:64b,Slot:15b,id:"minecraft:copper_ingot"},{Count:64b,Slot:16b,id:"minecraft:copper_ingot"},{Count:64b,Slot:17b,id:"minecraft:copper_ingot"},{Count:64b,Slot:18b,id:"minecraft:copper_ingot"},{Count:64b,Slot:19b,id:"minecraft:copper_ingot"},{Count:64b,Slot:20b,id:"minecraft:copper_ingot"},{Count:64b,Slot:21b,id:"minecraft:copper_ingot"},{Count:64b,Slot:22b,id:"minecraft:copper_ingot"},{Count:64b,Slot:23b,id:"minecraft:copper_ingot"},{Count:64b,Slot:24b,id:"minecraft:copper_ingot"},{Count:64b,Slot:25b,id:"minecraft:copper_ingot"},{Count:64b,Slot:26b,id:"minecraft:copper_ingot"}],id:"minecraft:shulker_box"}}'))

    //不想打字了
    
    singularity('kubejs:singularity_gold',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:gold_ingot"},{Count:64b,Slot:1b,id:"minecraft:gold_ingot"},{Count:64b,Slot:2b,id:"minecraft:gold_ingot"},{Count:64b,Slot:3b,id:"minecraft:gold_ingot"},{Count:64b,Slot:4b,id:"minecraft:gold_ingot"},{Count:64b,Slot:5b,id:"minecraft:gold_ingot"},{Count:64b,Slot:6b,id:"minecraft:gold_ingot"},{Count:64b,Slot:7b,id:"minecraft:gold_ingot"},{Count:64b,Slot:8b,id:"minecraft:gold_ingot"},{Count:64b,Slot:9b,id:"minecraft:gold_ingot"},{Count:64b,Slot:10b,id:"minecraft:gold_ingot"},{Count:64b,Slot:11b,id:"minecraft:gold_ingot"},{Count:64b,Slot:12b,id:"minecraft:gold_ingot"},{Count:64b,Slot:13b,id:"minecraft:gold_ingot"},{Count:64b,Slot:14b,id:"minecraft:gold_ingot"},{Count:64b,Slot:15b,id:"minecraft:gold_ingot"},{Count:64b,Slot:16b,id:"minecraft:gold_ingot"},{Count:64b,Slot:17b,id:"minecraft:gold_ingot"},{Count:64b,Slot:18b,id:"minecraft:gold_ingot"},{Count:64b,Slot:19b,id:"minecraft:gold_ingot"},{Count:64b,Slot:20b,id:"minecraft:gold_ingot"},{Count:64b,Slot:21b,id:"minecraft:gold_ingot"},{Count:64b,Slot:22b,id:"minecraft:gold_ingot"},{Count:64b,Slot:23b,id:"minecraft:gold_ingot"},{Count:64b,Slot:24b,id:"minecraft:gold_ingot"},{Count:64b,Slot:25b,id:"minecraft:gold_ingot"},{Count:64b,Slot:26b,id:"minecraft:gold_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_netherite',Item.of('minecraft:black_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:1b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:2b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:3b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:4b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:5b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:6b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:7b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:8b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:9b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:10b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:11b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:12b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:13b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:14b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:15b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:16b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:17b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:18b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:19b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:20b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:21b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:22b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:23b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:24b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:25b,id:"minecraft:netherite_ingot"},{Count:64b,Slot:26b,id:"minecraft:netherite_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_nether_star',Item.of('minecraft:white_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:nether_star"},{Count:64b,Slot:1b,id:"minecraft:nether_star"},{Count:64b,Slot:2b,id:"minecraft:nether_star"},{Count:64b,Slot:3b,id:"minecraft:nether_star"},{Count:64b,Slot:4b,id:"minecraft:nether_star"},{Count:64b,Slot:5b,id:"minecraft:nether_star"},{Count:64b,Slot:6b,id:"minecraft:nether_star"},{Count:64b,Slot:7b,id:"minecraft:nether_star"},{Count:64b,Slot:8b,id:"minecraft:nether_star"},{Count:64b,Slot:9b,id:"minecraft:nether_star"},{Count:64b,Slot:10b,id:"minecraft:nether_star"},{Count:64b,Slot:11b,id:"minecraft:nether_star"},{Count:64b,Slot:12b,id:"minecraft:nether_star"},{Count:64b,Slot:13b,id:"minecraft:nether_star"},{Count:64b,Slot:14b,id:"minecraft:nether_star"},{Count:64b,Slot:15b,id:"minecraft:nether_star"},{Count:64b,Slot:16b,id:"minecraft:nether_star"},{Count:64b,Slot:17b,id:"minecraft:nether_star"},{Count:64b,Slot:18b,id:"minecraft:nether_star"},{Count:64b,Slot:19b,id:"minecraft:nether_star"},{Count:64b,Slot:20b,id:"minecraft:nether_star"},{Count:64b,Slot:21b,id:"minecraft:nether_star"},{Count:64b,Slot:22b,id:"minecraft:nether_star"},{Count:64b,Slot:23b,id:"minecraft:nether_star"},{Count:64b,Slot:24b,id:"minecraft:nether_star"},{Count:64b,Slot:25b,id:"minecraft:nether_star"},{Count:64b,Slot:26b,id:"minecraft:nether_star"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_signalum',Item.of('minecraft:red_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:signalum_ingot"},{Count:64b,Slot:1b,id:"thermal:signalum_ingot"},{Count:64b,Slot:2b,id:"thermal:signalum_ingot"},{Count:64b,Slot:3b,id:"thermal:signalum_ingot"},{Count:64b,Slot:4b,id:"thermal:signalum_ingot"},{Count:64b,Slot:5b,id:"thermal:signalum_ingot"},{Count:64b,Slot:6b,id:"thermal:signalum_ingot"},{Count:64b,Slot:7b,id:"thermal:signalum_ingot"},{Count:64b,Slot:8b,id:"thermal:signalum_ingot"},{Count:64b,Slot:9b,id:"thermal:signalum_ingot"},{Count:64b,Slot:10b,id:"thermal:signalum_ingot"},{Count:64b,Slot:11b,id:"thermal:signalum_ingot"},{Count:64b,Slot:12b,id:"thermal:signalum_ingot"},{Count:64b,Slot:13b,id:"thermal:signalum_ingot"},{Count:64b,Slot:14b,id:"thermal:signalum_ingot"},{Count:64b,Slot:15b,id:"thermal:signalum_ingot"},{Count:64b,Slot:16b,id:"thermal:signalum_ingot"},{Count:64b,Slot:17b,id:"thermal:signalum_ingot"},{Count:64b,Slot:18b,id:"thermal:signalum_ingot"},{Count:64b,Slot:19b,id:"thermal:signalum_ingot"},{Count:64b,Slot:20b,id:"thermal:signalum_ingot"},{Count:64b,Slot:21b,id:"thermal:signalum_ingot"},{Count:64b,Slot:22b,id:"thermal:signalum_ingot"},{Count:64b,Slot:23b,id:"thermal:signalum_ingot"},{Count:64b,Slot:24b,id:"thermal:signalum_ingot"},{Count:64b,Slot:25b,id:"thermal:signalum_ingot"},{Count:64b,Slot:26b,id:"thermal:signalum_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_lumium',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:lumium_ingot"},{Count:64b,Slot:1b,id:"thermal:lumium_ingot"},{Count:64b,Slot:2b,id:"thermal:lumium_ingot"},{Count:64b,Slot:3b,id:"thermal:lumium_ingot"},{Count:64b,Slot:4b,id:"thermal:lumium_ingot"},{Count:64b,Slot:5b,id:"thermal:lumium_ingot"},{Count:64b,Slot:6b,id:"thermal:lumium_ingot"},{Count:64b,Slot:7b,id:"thermal:lumium_ingot"},{Count:64b,Slot:8b,id:"thermal:lumium_ingot"},{Count:64b,Slot:9b,id:"thermal:lumium_ingot"},{Count:64b,Slot:10b,id:"thermal:lumium_ingot"},{Count:64b,Slot:11b,id:"thermal:lumium_ingot"},{Count:64b,Slot:12b,id:"thermal:lumium_ingot"},{Count:64b,Slot:13b,id:"thermal:lumium_ingot"},{Count:64b,Slot:14b,id:"thermal:lumium_ingot"},{Count:64b,Slot:15b,id:"thermal:lumium_ingot"},{Count:64b,Slot:16b,id:"thermal:lumium_ingot"},{Count:64b,Slot:17b,id:"thermal:lumium_ingot"},{Count:64b,Slot:18b,id:"thermal:lumium_ingot"},{Count:64b,Slot:19b,id:"thermal:lumium_ingot"},{Count:64b,Slot:20b,id:"thermal:lumium_ingot"},{Count:64b,Slot:21b,id:"thermal:lumium_ingot"},{Count:64b,Slot:22b,id:"thermal:lumium_ingot"},{Count:64b,Slot:23b,id:"thermal:lumium_ingot"},{Count:64b,Slot:24b,id:"thermal:lumium_ingot"},{Count:64b,Slot:25b,id:"thermal:lumium_ingot"},{Count:64b,Slot:26b,id:"thermal:lumium_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_enderium',Item.of('minecraft:purple_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:enderium_ingot"},{Count:64b,Slot:1b,id:"thermal:enderium_ingot"},{Count:64b,Slot:2b,id:"thermal:enderium_ingot"},{Count:64b,Slot:3b,id:"thermal:enderium_ingot"},{Count:64b,Slot:4b,id:"thermal:enderium_ingot"},{Count:64b,Slot:5b,id:"thermal:enderium_ingot"},{Count:64b,Slot:6b,id:"thermal:enderium_ingot"},{Count:64b,Slot:7b,id:"thermal:enderium_ingot"},{Count:64b,Slot:8b,id:"thermal:enderium_ingot"},{Count:64b,Slot:9b,id:"thermal:enderium_ingot"},{Count:64b,Slot:10b,id:"thermal:enderium_ingot"},{Count:64b,Slot:11b,id:"thermal:enderium_ingot"},{Count:64b,Slot:12b,id:"thermal:enderium_ingot"},{Count:64b,Slot:13b,id:"thermal:enderium_ingot"},{Count:64b,Slot:14b,id:"thermal:enderium_ingot"},{Count:64b,Slot:15b,id:"thermal:enderium_ingot"},{Count:64b,Slot:16b,id:"thermal:enderium_ingot"},{Count:64b,Slot:17b,id:"thermal:enderium_ingot"},{Count:64b,Slot:18b,id:"thermal:enderium_ingot"},{Count:64b,Slot:19b,id:"thermal:enderium_ingot"},{Count:64b,Slot:20b,id:"thermal:enderium_ingot"},{Count:64b,Slot:21b,id:"thermal:enderium_ingot"},{Count:64b,Slot:22b,id:"thermal:enderium_ingot"},{Count:64b,Slot:23b,id:"thermal:enderium_ingot"},{Count:64b,Slot:24b,id:"thermal:enderium_ingot"},{Count:64b,Slot:25b,id:"thermal:enderium_ingot"},{Count:64b,Slot:26b,id:"thermal:enderium_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_tin',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:tin_ingot"},{Count:64b,Slot:1b,id:"thermal:tin_ingot"},{Count:64b,Slot:2b,id:"thermal:tin_ingot"},{Count:64b,Slot:3b,id:"thermal:tin_ingot"},{Count:64b,Slot:4b,id:"thermal:tin_ingot"},{Count:64b,Slot:5b,id:"thermal:tin_ingot"},{Count:64b,Slot:6b,id:"thermal:tin_ingot"},{Count:64b,Slot:7b,id:"thermal:tin_ingot"},{Count:64b,Slot:8b,id:"thermal:tin_ingot"},{Count:64b,Slot:9b,id:"thermal:tin_ingot"},{Count:64b,Slot:10b,id:"thermal:tin_ingot"},{Count:64b,Slot:11b,id:"thermal:tin_ingot"},{Count:64b,Slot:12b,id:"thermal:tin_ingot"},{Count:64b,Slot:13b,id:"thermal:tin_ingot"},{Count:64b,Slot:14b,id:"thermal:tin_ingot"},{Count:64b,Slot:15b,id:"thermal:tin_ingot"},{Count:64b,Slot:16b,id:"thermal:tin_ingot"},{Count:64b,Slot:17b,id:"thermal:tin_ingot"},{Count:64b,Slot:18b,id:"thermal:tin_ingot"},{Count:64b,Slot:19b,id:"thermal:tin_ingot"},{Count:64b,Slot:20b,id:"thermal:tin_ingot"},{Count:64b,Slot:21b,id:"thermal:tin_ingot"},{Count:64b,Slot:22b,id:"thermal:tin_ingot"},{Count:64b,Slot:23b,id:"thermal:tin_ingot"},{Count:64b,Slot:24b,id:"thermal:tin_ingot"},{Count:64b,Slot:25b,id:"thermal:tin_ingot"},{Count:64b,Slot:26b,id:"thermal:tin_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_lead',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:ingot_lead"},{Count:64b,Slot:1b,id:"mekanism:ingot_lead"},{Count:64b,Slot:2b,id:"mekanism:ingot_lead"},{Count:64b,Slot:3b,id:"mekanism:ingot_lead"},{Count:64b,Slot:4b,id:"mekanism:ingot_lead"},{Count:64b,Slot:5b,id:"mekanism:ingot_lead"},{Count:64b,Slot:6b,id:"mekanism:ingot_lead"},{Count:64b,Slot:7b,id:"mekanism:ingot_lead"},{Count:64b,Slot:8b,id:"mekanism:ingot_lead"},{Count:64b,Slot:9b,id:"mekanism:ingot_lead"},{Count:64b,Slot:10b,id:"mekanism:ingot_lead"},{Count:64b,Slot:11b,id:"mekanism:ingot_lead"},{Count:64b,Slot:12b,id:"mekanism:ingot_lead"},{Count:64b,Slot:13b,id:"mekanism:ingot_lead"},{Count:64b,Slot:14b,id:"mekanism:ingot_lead"},{Count:64b,Slot:15b,id:"mekanism:ingot_lead"},{Count:64b,Slot:16b,id:"mekanism:ingot_lead"},{Count:64b,Slot:17b,id:"mekanism:ingot_lead"},{Count:64b,Slot:18b,id:"mekanism:ingot_lead"},{Count:64b,Slot:19b,id:"mekanism:ingot_lead"},{Count:64b,Slot:20b,id:"mekanism:ingot_lead"},{Count:64b,Slot:21b,id:"mekanism:ingot_lead"},{Count:64b,Slot:22b,id:"mekanism:ingot_lead"},{Count:64b,Slot:23b,id:"mekanism:ingot_lead"},{Count:64b,Slot:24b,id:"mekanism:ingot_lead"},{Count:64b,Slot:25b,id:"mekanism:ingot_lead"},{Count:64b,Slot:26b,id:"mekanism:ingot_lead"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_silver',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:silver_ingot"},{Count:64b,Slot:1b,id:"thermal:silver_ingot"},{Count:64b,Slot:2b,id:"thermal:silver_ingot"},{Count:64b,Slot:3b,id:"thermal:silver_ingot"},{Count:64b,Slot:4b,id:"thermal:silver_ingot"},{Count:64b,Slot:5b,id:"thermal:silver_ingot"},{Count:64b,Slot:6b,id:"thermal:silver_ingot"},{Count:64b,Slot:7b,id:"thermal:silver_ingot"},{Count:64b,Slot:8b,id:"thermal:silver_ingot"},{Count:64b,Slot:9b,id:"thermal:silver_ingot"},{Count:64b,Slot:10b,id:"thermal:silver_ingot"},{Count:64b,Slot:11b,id:"thermal:silver_ingot"},{Count:64b,Slot:12b,id:"thermal:silver_ingot"},{Count:64b,Slot:13b,id:"thermal:silver_ingot"},{Count:64b,Slot:14b,id:"thermal:silver_ingot"},{Count:64b,Slot:15b,id:"thermal:silver_ingot"},{Count:64b,Slot:16b,id:"thermal:silver_ingot"},{Count:64b,Slot:17b,id:"thermal:silver_ingot"},{Count:64b,Slot:18b,id:"thermal:silver_ingot"},{Count:64b,Slot:19b,id:"thermal:silver_ingot"},{Count:64b,Slot:20b,id:"thermal:silver_ingot"},{Count:64b,Slot:21b,id:"thermal:silver_ingot"},{Count:64b,Slot:22b,id:"thermal:silver_ingot"},{Count:64b,Slot:23b,id:"thermal:silver_ingot"},{Count:64b,Slot:24b,id:"thermal:silver_ingot"},{Count:64b,Slot:25b,id:"thermal:silver_ingot"},{Count:64b,Slot:26b,id:"thermal:silver_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_bronze',Item.of('minecraft:orange_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:bronze_ingot"},{Count:64b,Slot:1b,id:"thermal:bronze_ingot"},{Count:64b,Slot:2b,id:"thermal:bronze_ingot"},{Count:64b,Slot:3b,id:"thermal:bronze_ingot"},{Count:64b,Slot:4b,id:"thermal:bronze_ingot"},{Count:64b,Slot:5b,id:"thermal:bronze_ingot"},{Count:64b,Slot:6b,id:"thermal:bronze_ingot"},{Count:64b,Slot:7b,id:"thermal:bronze_ingot"},{Count:64b,Slot:8b,id:"thermal:bronze_ingot"},{Count:64b,Slot:9b,id:"thermal:bronze_ingot"},{Count:64b,Slot:10b,id:"thermal:bronze_ingot"},{Count:64b,Slot:11b,id:"thermal:bronze_ingot"},{Count:64b,Slot:12b,id:"thermal:bronze_ingot"},{Count:64b,Slot:13b,id:"thermal:bronze_ingot"},{Count:64b,Slot:14b,id:"thermal:bronze_ingot"},{Count:64b,Slot:15b,id:"thermal:bronze_ingot"},{Count:64b,Slot:16b,id:"thermal:bronze_ingot"},{Count:64b,Slot:17b,id:"thermal:bronze_ingot"},{Count:64b,Slot:18b,id:"thermal:bronze_ingot"},{Count:64b,Slot:19b,id:"thermal:bronze_ingot"},{Count:64b,Slot:20b,id:"thermal:bronze_ingot"},{Count:64b,Slot:21b,id:"thermal:bronze_ingot"},{Count:64b,Slot:22b,id:"thermal:bronze_ingot"},{Count:64b,Slot:23b,id:"thermal:bronze_ingot"},{Count:64b,Slot:24b,id:"thermal:bronze_ingot"},{Count:64b,Slot:25b,id:"thermal:bronze_ingot"},{Count:64b,Slot:26b,id:"thermal:bronze_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_electrum',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:electrum_ingot"},{Count:64b,Slot:1b,id:"thermal:electrum_ingot"},{Count:64b,Slot:2b,id:"thermal:electrum_ingot"},{Count:64b,Slot:3b,id:"thermal:electrum_ingot"},{Count:64b,Slot:4b,id:"thermal:electrum_ingot"},{Count:64b,Slot:5b,id:"thermal:electrum_ingot"},{Count:64b,Slot:6b,id:"thermal:electrum_ingot"},{Count:64b,Slot:7b,id:"thermal:electrum_ingot"},{Count:64b,Slot:8b,id:"thermal:electrum_ingot"},{Count:64b,Slot:9b,id:"thermal:electrum_ingot"},{Count:64b,Slot:10b,id:"thermal:electrum_ingot"},{Count:64b,Slot:11b,id:"thermal:electrum_ingot"},{Count:64b,Slot:12b,id:"thermal:electrum_ingot"},{Count:64b,Slot:13b,id:"thermal:electrum_ingot"},{Count:64b,Slot:14b,id:"thermal:electrum_ingot"},{Count:64b,Slot:15b,id:"thermal:electrum_ingot"},{Count:64b,Slot:16b,id:"thermal:electrum_ingot"},{Count:64b,Slot:17b,id:"thermal:electrum_ingot"},{Count:64b,Slot:18b,id:"thermal:electrum_ingot"},{Count:64b,Slot:19b,id:"thermal:electrum_ingot"},{Count:64b,Slot:20b,id:"thermal:electrum_ingot"},{Count:64b,Slot:21b,id:"thermal:electrum_ingot"},{Count:64b,Slot:22b,id:"thermal:electrum_ingot"},{Count:64b,Slot:23b,id:"thermal:electrum_ingot"},{Count:64b,Slot:24b,id:"thermal:electrum_ingot"},{Count:64b,Slot:25b,id:"thermal:electrum_ingot"},{Count:64b,Slot:26b,id:"thermal:electrum_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_invar',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:invar_ingot"},{Count:64b,Slot:1b,id:"thermal:invar_ingot"},{Count:64b,Slot:2b,id:"thermal:invar_ingot"},{Count:64b,Slot:3b,id:"thermal:invar_ingot"},{Count:64b,Slot:4b,id:"thermal:invar_ingot"},{Count:64b,Slot:5b,id:"thermal:invar_ingot"},{Count:64b,Slot:6b,id:"thermal:invar_ingot"},{Count:64b,Slot:7b,id:"thermal:invar_ingot"},{Count:64b,Slot:8b,id:"thermal:invar_ingot"},{Count:64b,Slot:9b,id:"thermal:invar_ingot"},{Count:64b,Slot:10b,id:"thermal:invar_ingot"},{Count:64b,Slot:11b,id:"thermal:invar_ingot"},{Count:64b,Slot:12b,id:"thermal:invar_ingot"},{Count:64b,Slot:13b,id:"thermal:invar_ingot"},{Count:64b,Slot:14b,id:"thermal:invar_ingot"},{Count:64b,Slot:15b,id:"thermal:invar_ingot"},{Count:64b,Slot:16b,id:"thermal:invar_ingot"},{Count:64b,Slot:17b,id:"thermal:invar_ingot"},{Count:64b,Slot:18b,id:"thermal:invar_ingot"},{Count:64b,Slot:19b,id:"thermal:invar_ingot"},{Count:64b,Slot:20b,id:"thermal:invar_ingot"},{Count:64b,Slot:21b,id:"thermal:invar_ingot"},{Count:64b,Slot:22b,id:"thermal:invar_ingot"},{Count:64b,Slot:23b,id:"thermal:invar_ingot"},{Count:64b,Slot:24b,id:"thermal:invar_ingot"},{Count:64b,Slot:25b,id:"thermal:invar_ingot"},{Count:64b,Slot:26b,id:"thermal:invar_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_constantan',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:constantan_ingot"},{Count:64b,Slot:1b,id:"thermal:constantan_ingot"},{Count:64b,Slot:2b,id:"thermal:constantan_ingot"},{Count:64b,Slot:3b,id:"thermal:constantan_ingot"},{Count:64b,Slot:4b,id:"thermal:constantan_ingot"},{Count:64b,Slot:5b,id:"thermal:constantan_ingot"},{Count:64b,Slot:6b,id:"thermal:constantan_ingot"},{Count:64b,Slot:7b,id:"thermal:constantan_ingot"},{Count:64b,Slot:8b,id:"thermal:constantan_ingot"},{Count:64b,Slot:9b,id:"thermal:constantan_ingot"},{Count:64b,Slot:10b,id:"thermal:constantan_ingot"},{Count:64b,Slot:11b,id:"thermal:constantan_ingot"},{Count:64b,Slot:12b,id:"thermal:constantan_ingot"},{Count:64b,Slot:13b,id:"thermal:constantan_ingot"},{Count:64b,Slot:14b,id:"thermal:constantan_ingot"},{Count:64b,Slot:15b,id:"thermal:constantan_ingot"},{Count:64b,Slot:16b,id:"thermal:constantan_ingot"},{Count:64b,Slot:17b,id:"thermal:constantan_ingot"},{Count:64b,Slot:18b,id:"thermal:constantan_ingot"},{Count:64b,Slot:19b,id:"thermal:constantan_ingot"},{Count:64b,Slot:20b,id:"thermal:constantan_ingot"},{Count:64b,Slot:21b,id:"thermal:constantan_ingot"},{Count:64b,Slot:22b,id:"thermal:constantan_ingot"},{Count:64b,Slot:23b,id:"thermal:constantan_ingot"},{Count:64b,Slot:24b,id:"thermal:constantan_ingot"},{Count:64b,Slot:25b,id:"thermal:constantan_ingot"},{Count:64b,Slot:26b,id:"thermal:constantan_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_aluminum',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:1b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:2b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:3b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:4b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:5b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:6b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:7b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:8b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:9b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:10b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:11b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:12b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:13b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:14b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:15b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:16b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:17b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:18b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:19b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:20b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:21b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:22b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:23b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:24b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:25b,id:"immersiveengineering:ingot_aluminum"},{Count:64b,Slot:26b,id:"immersiveengineering:ingot_aluminum"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_purpur',Item.of('minecraft:purple_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:1b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:2b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:3b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:4b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:5b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:6b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:7b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:8b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:9b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:10b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:11b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:12b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:13b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:14b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:15b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:16b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:17b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:18b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:19b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:20b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:21b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:22b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:23b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:24b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:25b,id:"kubejs:purpur_ingot"},{Count:64b,Slot:26b,id:"kubejs:purpur_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_refined_obsidian',Item.of('minecraft:purple_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:1b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:2b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:3b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:4b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:5b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:6b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:7b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:8b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:9b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:10b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:11b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:12b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:13b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:14b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:15b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:16b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:17b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:18b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:19b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:20b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:21b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:22b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:23b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:24b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:25b,id:"mekanism:ingot_refined_obsidian"},{Count:64b,Slot:26b,id:"mekanism:ingot_refined_obsidian"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_refined_glowstone',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:1b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:2b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:3b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:4b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:5b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:6b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:7b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:8b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:9b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:10b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:11b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:12b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:13b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:14b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:15b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:16b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:17b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:18b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:19b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:20b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:21b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:22b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:23b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:24b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:25b,id:"mekanism:ingot_refined_glowstone"},{Count:64b,Slot:26b,id:"mekanism:ingot_refined_glowstone"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_osmium',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:1b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:2b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:3b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:4b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:5b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:6b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:7b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:8b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:9b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:10b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:11b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:12b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:13b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:14b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:15b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:16b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:17b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:18b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:19b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:20b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:21b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:22b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:23b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:24b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:25b,id:"mekanism:ingot_osmium"},{Count:64b,Slot:26b,id:"mekanism:ingot_osmium"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_andeside_alloy',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:andesite_alloy"},{Count:64b,Slot:1b,id:"create:andesite_alloy"},{Count:64b,Slot:2b,id:"create:andesite_alloy"},{Count:64b,Slot:3b,id:"create:andesite_alloy"},{Count:64b,Slot:4b,id:"create:andesite_alloy"},{Count:64b,Slot:5b,id:"create:andesite_alloy"},{Count:64b,Slot:6b,id:"create:andesite_alloy"},{Count:64b,Slot:7b,id:"create:andesite_alloy"},{Count:64b,Slot:8b,id:"create:andesite_alloy"},{Count:64b,Slot:9b,id:"create:andesite_alloy"},{Count:64b,Slot:10b,id:"create:andesite_alloy"},{Count:64b,Slot:11b,id:"create:andesite_alloy"},{Count:64b,Slot:12b,id:"create:andesite_alloy"},{Count:64b,Slot:13b,id:"create:andesite_alloy"},{Count:64b,Slot:14b,id:"create:andesite_alloy"},{Count:64b,Slot:15b,id:"create:andesite_alloy"},{Count:64b,Slot:16b,id:"create:andesite_alloy"},{Count:64b,Slot:17b,id:"create:andesite_alloy"},{Count:64b,Slot:18b,id:"create:andesite_alloy"},{Count:64b,Slot:19b,id:"create:andesite_alloy"},{Count:64b,Slot:20b,id:"create:andesite_alloy"},{Count:64b,Slot:21b,id:"create:andesite_alloy"},{Count:64b,Slot:22b,id:"create:andesite_alloy"},{Count:64b,Slot:23b,id:"create:andesite_alloy"},{Count:64b,Slot:24b,id:"create:andesite_alloy"},{Count:64b,Slot:25b,id:"create:andesite_alloy"},{Count:64b,Slot:26b,id:"create:andesite_alloy"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_zinc',Item.of('minecraft:lime_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:zinc_ingot"},{Count:64b,Slot:1b,id:"create:zinc_ingot"},{Count:64b,Slot:2b,id:"create:zinc_ingot"},{Count:64b,Slot:3b,id:"create:zinc_ingot"},{Count:64b,Slot:4b,id:"create:zinc_ingot"},{Count:64b,Slot:5b,id:"create:zinc_ingot"},{Count:64b,Slot:6b,id:"create:zinc_ingot"},{Count:64b,Slot:7b,id:"create:zinc_ingot"},{Count:64b,Slot:8b,id:"create:zinc_ingot"},{Count:64b,Slot:9b,id:"create:zinc_ingot"},{Count:64b,Slot:10b,id:"create:zinc_ingot"},{Count:64b,Slot:11b,id:"create:zinc_ingot"},{Count:64b,Slot:12b,id:"create:zinc_ingot"},{Count:64b,Slot:13b,id:"create:zinc_ingot"},{Count:64b,Slot:14b,id:"create:zinc_ingot"},{Count:64b,Slot:15b,id:"create:zinc_ingot"},{Count:64b,Slot:16b,id:"create:zinc_ingot"},{Count:64b,Slot:17b,id:"create:zinc_ingot"},{Count:64b,Slot:18b,id:"create:zinc_ingot"},{Count:64b,Slot:19b,id:"create:zinc_ingot"},{Count:64b,Slot:20b,id:"create:zinc_ingot"},{Count:64b,Slot:21b,id:"create:zinc_ingot"},{Count:64b,Slot:22b,id:"create:zinc_ingot"},{Count:64b,Slot:23b,id:"create:zinc_ingot"},{Count:64b,Slot:24b,id:"create:zinc_ingot"},{Count:64b,Slot:25b,id:"create:zinc_ingot"},{Count:64b,Slot:26b,id:"create:zinc_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_brass',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:brass_ingot"},{Count:64b,Slot:1b,id:"create:brass_ingot"},{Count:64b,Slot:2b,id:"create:brass_ingot"},{Count:64b,Slot:3b,id:"create:brass_ingot"},{Count:64b,Slot:4b,id:"create:brass_ingot"},{Count:64b,Slot:5b,id:"create:brass_ingot"},{Count:64b,Slot:6b,id:"create:brass_ingot"},{Count:64b,Slot:7b,id:"create:brass_ingot"},{Count:64b,Slot:8b,id:"create:brass_ingot"},{Count:64b,Slot:9b,id:"create:brass_ingot"},{Count:64b,Slot:10b,id:"create:brass_ingot"},{Count:64b,Slot:11b,id:"create:brass_ingot"},{Count:64b,Slot:12b,id:"create:brass_ingot"},{Count:64b,Slot:13b,id:"create:brass_ingot"},{Count:64b,Slot:14b,id:"create:brass_ingot"},{Count:64b,Slot:15b,id:"create:brass_ingot"},{Count:64b,Slot:16b,id:"create:brass_ingot"},{Count:64b,Slot:17b,id:"create:brass_ingot"},{Count:64b,Slot:18b,id:"create:brass_ingot"},{Count:64b,Slot:19b,id:"create:brass_ingot"},{Count:64b,Slot:20b,id:"create:brass_ingot"},{Count:64b,Slot:21b,id:"create:brass_ingot"},{Count:64b,Slot:22b,id:"create:brass_ingot"},{Count:64b,Slot:23b,id:"create:brass_ingot"},{Count:64b,Slot:24b,id:"create:brass_ingot"},{Count:64b,Slot:25b,id:"create:brass_ingot"},{Count:64b,Slot:26b,id:"create:brass_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_compositesteel',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:1b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:2b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:3b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:4b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:5b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:6b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:7b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:8b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:9b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:10b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:11b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:12b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:13b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:14b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:15b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:16b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:17b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:18b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:19b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:20b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:21b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:22b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:23b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:24b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:25b,id:"kubejs:compositesteel_ingot"},{Count:64b,Slot:26b,id:"kubejs:compositesteel_ingot"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_fluix',Item.of('minecraft:purple_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"ae2:fluix_crystal"},{Count:64b,Slot:1b,id:"ae2:fluix_crystal"},{Count:64b,Slot:2b,id:"ae2:fluix_crystal"},{Count:64b,Slot:3b,id:"ae2:fluix_crystal"},{Count:64b,Slot:4b,id:"ae2:fluix_crystal"},{Count:64b,Slot:5b,id:"ae2:fluix_crystal"},{Count:64b,Slot:6b,id:"ae2:fluix_crystal"},{Count:64b,Slot:7b,id:"ae2:fluix_crystal"},{Count:64b,Slot:8b,id:"ae2:fluix_crystal"},{Count:64b,Slot:9b,id:"ae2:fluix_crystal"},{Count:64b,Slot:10b,id:"ae2:fluix_crystal"},{Count:64b,Slot:11b,id:"ae2:fluix_crystal"},{Count:64b,Slot:12b,id:"ae2:fluix_crystal"},{Count:64b,Slot:13b,id:"ae2:fluix_crystal"},{Count:64b,Slot:14b,id:"ae2:fluix_crystal"},{Count:64b,Slot:15b,id:"ae2:fluix_crystal"},{Count:64b,Slot:16b,id:"ae2:fluix_crystal"},{Count:64b,Slot:17b,id:"ae2:fluix_crystal"},{Count:64b,Slot:18b,id:"ae2:fluix_crystal"},{Count:64b,Slot:19b,id:"ae2:fluix_crystal"},{Count:64b,Slot:20b,id:"ae2:fluix_crystal"},{Count:64b,Slot:21b,id:"ae2:fluix_crystal"},{Count:64b,Slot:22b,id:"ae2:fluix_crystal"},{Count:64b,Slot:23b,id:"ae2:fluix_crystal"},{Count:64b,Slot:24b,id:"ae2:fluix_crystal"},{Count:64b,Slot:25b,id:"ae2:fluix_crystal"},{Count:64b,Slot:26b,id:"ae2:fluix_crystal"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_lapis',Item.of('minecraft:blue_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:1b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:2b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:3b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:4b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:5b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:6b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:7b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:8b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:9b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:10b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:11b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:12b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:13b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:14b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:15b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:16b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:17b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:18b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:19b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:20b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:21b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:22b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:23b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:24b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:25b,id:"minecraft:lapis_lazuli"},{Count:64b,Slot:26b,id:"minecraft:lapis_lazuli"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_singularity',Item.of('minecraft:blue_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"ae2:singularity"},{Count:64b,Slot:1b,id:"ae2:singularity"},{Count:64b,Slot:2b,id:"ae2:singularity"},{Count:64b,Slot:3b,id:"ae2:singularity"},{Count:64b,Slot:4b,id:"ae2:singularity"},{Count:64b,Slot:5b,id:"ae2:singularity"},{Count:64b,Slot:6b,id:"ae2:singularity"},{Count:64b,Slot:7b,id:"ae2:singularity"},{Count:64b,Slot:8b,id:"ae2:singularity"},{Count:64b,Slot:9b,id:"ae2:singularity"},{Count:64b,Slot:10b,id:"ae2:singularity"},{Count:64b,Slot:11b,id:"ae2:singularity"},{Count:64b,Slot:12b,id:"ae2:singularity"},{Count:64b,Slot:13b,id:"ae2:singularity"},{Count:64b,Slot:14b,id:"ae2:singularity"},{Count:64b,Slot:15b,id:"ae2:singularity"},{Count:64b,Slot:16b,id:"ae2:singularity"},{Count:64b,Slot:17b,id:"ae2:singularity"},{Count:64b,Slot:18b,id:"ae2:singularity"},{Count:64b,Slot:19b,id:"ae2:singularity"},{Count:64b,Slot:20b,id:"ae2:singularity"},{Count:64b,Slot:21b,id:"ae2:singularity"},{Count:64b,Slot:22b,id:"ae2:singularity"},{Count:64b,Slot:23b,id:"ae2:singularity"},{Count:64b,Slot:24b,id:"ae2:singularity"},{Count:64b,Slot:25b,id:"ae2:singularity"},{Count:64b,Slot:26b,id:"ae2:singularity"}],id:"minecraft:shulker_box"}}'))

    //
    singularity('kubejs:singularity_silicon',Item.of('minecraft:black_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"ae2:silicon"},{Count:64b,Slot:1b,id:"ae2:silicon"},{Count:64b,Slot:2b,id:"ae2:silicon"},{Count:64b,Slot:3b,id:"ae2:silicon"},{Count:64b,Slot:4b,id:"ae2:silicon"},{Count:64b,Slot:5b,id:"ae2:silicon"},{Count:64b,Slot:6b,id:"ae2:silicon"},{Count:64b,Slot:7b,id:"ae2:silicon"},{Count:64b,Slot:8b,id:"ae2:silicon"},{Count:64b,Slot:9b,id:"ae2:silicon"},{Count:64b,Slot:10b,id:"ae2:silicon"},{Count:64b,Slot:11b,id:"ae2:silicon"},{Count:64b,Slot:12b,id:"ae2:silicon"},{Count:64b,Slot:13b,id:"ae2:silicon"},{Count:64b,Slot:14b,id:"ae2:silicon"},{Count:64b,Slot:15b,id:"ae2:silicon"},{Count:64b,Slot:16b,id:"ae2:silicon"},{Count:64b,Slot:17b,id:"ae2:silicon"},{Count:64b,Slot:18b,id:"ae2:silicon"},{Count:64b,Slot:19b,id:"ae2:silicon"},{Count:64b,Slot:20b,id:"ae2:silicon"},{Count:64b,Slot:21b,id:"ae2:silicon"},{Count:64b,Slot:22b,id:"ae2:silicon"},{Count:64b,Slot:23b,id:"ae2:silicon"},{Count:64b,Slot:24b,id:"ae2:silicon"},{Count:64b,Slot:25b,id:"ae2:silicon"},{Count:64b,Slot:26b,id:"ae2:silicon"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_wool',Item.of('minecraft:white_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:white_wool"},{Count:64b,Slot:1b,id:"minecraft:white_wool"},{Count:64b,Slot:2b,id:"minecraft:white_wool"},{Count:64b,Slot:3b,id:"minecraft:white_wool"},{Count:64b,Slot:4b,id:"minecraft:white_wool"},{Count:64b,Slot:5b,id:"minecraft:white_wool"},{Count:64b,Slot:6b,id:"minecraft:white_wool"},{Count:64b,Slot:7b,id:"minecraft:white_wool"},{Count:64b,Slot:8b,id:"minecraft:white_wool"},{Count:64b,Slot:9b,id:"minecraft:white_wool"},{Count:64b,Slot:10b,id:"minecraft:white_wool"},{Count:64b,Slot:11b,id:"minecraft:white_wool"},{Count:64b,Slot:12b,id:"minecraft:white_wool"},{Count:64b,Slot:13b,id:"minecraft:white_wool"},{Count:64b,Slot:14b,id:"minecraft:white_wool"},{Count:64b,Slot:15b,id:"minecraft:white_wool"},{Count:64b,Slot:16b,id:"minecraft:white_wool"},{Count:64b,Slot:17b,id:"minecraft:white_wool"},{Count:64b,Slot:18b,id:"minecraft:white_wool"},{Count:64b,Slot:19b,id:"minecraft:white_wool"},{Count:64b,Slot:20b,id:"minecraft:white_wool"},{Count:64b,Slot:21b,id:"minecraft:white_wool"},{Count:64b,Slot:22b,id:"minecraft:white_wool"},{Count:64b,Slot:23b,id:"minecraft:white_wool"},{Count:64b,Slot:24b,id:"minecraft:white_wool"},{Count:64b,Slot:25b,id:"minecraft:white_wool"},{Count:64b,Slot:26b,id:"minecraft:white_wool"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_blaze',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"botania:blaze_block"},{Count:64b,Slot:1b,id:"botania:blaze_block"},{Count:64b,Slot:2b,id:"botania:blaze_block"},{Count:64b,Slot:3b,id:"botania:blaze_block"},{Count:64b,Slot:4b,id:"botania:blaze_block"},{Count:64b,Slot:5b,id:"botania:blaze_block"},{Count:64b,Slot:6b,id:"botania:blaze_block"},{Count:64b,Slot:7b,id:"botania:blaze_block"},{Count:64b,Slot:8b,id:"botania:blaze_block"},{Count:64b,Slot:9b,id:"botania:blaze_block"},{Count:64b,Slot:10b,id:"botania:blaze_block"},{Count:64b,Slot:11b,id:"botania:blaze_block"},{Count:64b,Slot:12b,id:"botania:blaze_block"},{Count:64b,Slot:13b,id:"botania:blaze_block"},{Count:64b,Slot:14b,id:"botania:blaze_block"},{Count:64b,Slot:15b,id:"botania:blaze_block"},{Count:64b,Slot:16b,id:"botania:blaze_block"},{Count:64b,Slot:17b,id:"botania:blaze_block"},{Count:64b,Slot:18b,id:"botania:blaze_block"},{Count:64b,Slot:19b,id:"botania:blaze_block"},{Count:64b,Slot:20b,id:"botania:blaze_block"},{Count:64b,Slot:21b,id:"botania:blaze_block"},{Count:64b,Slot:22b,id:"botania:blaze_block"},{Count:64b,Slot:23b,id:"botania:blaze_block"},{Count:64b,Slot:24b,id:"botania:blaze_block"},{Count:64b,Slot:25b,id:"botania:blaze_block"},{Count:64b,Slot:26b,id:"botania:blaze_block"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_mycelium',Item.of('minecraft:purple_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:mycelium"},{Count:64b,Slot:1b,id:"minecraft:mycelium"},{Count:64b,Slot:2b,id:"minecraft:mycelium"},{Count:64b,Slot:3b,id:"minecraft:mycelium"},{Count:64b,Slot:4b,id:"minecraft:mycelium"},{Count:64b,Slot:5b,id:"minecraft:mycelium"},{Count:64b,Slot:6b,id:"minecraft:mycelium"},{Count:64b,Slot:7b,id:"minecraft:mycelium"},{Count:64b,Slot:8b,id:"minecraft:mycelium"},{Count:64b,Slot:9b,id:"minecraft:mycelium"},{Count:64b,Slot:10b,id:"minecraft:mycelium"},{Count:64b,Slot:11b,id:"minecraft:mycelium"},{Count:64b,Slot:12b,id:"minecraft:mycelium"},{Count:64b,Slot:13b,id:"minecraft:mycelium"},{Count:64b,Slot:14b,id:"minecraft:mycelium"},{Count:64b,Slot:15b,id:"minecraft:mycelium"},{Count:64b,Slot:16b,id:"minecraft:mycelium"},{Count:64b,Slot:17b,id:"minecraft:mycelium"},{Count:64b,Slot:18b,id:"minecraft:mycelium"},{Count:64b,Slot:19b,id:"minecraft:mycelium"},{Count:64b,Slot:20b,id:"minecraft:mycelium"},{Count:64b,Slot:21b,id:"minecraft:mycelium"},{Count:64b,Slot:22b,id:"minecraft:mycelium"},{Count:64b,Slot:23b,id:"minecraft:mycelium"},{Count:64b,Slot:24b,id:"minecraft:mycelium"},{Count:64b,Slot:25b,id:"minecraft:mycelium"},{Count:64b,Slot:26b,id:"minecraft:mycelium"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_living_wood',Item.of('minecraft:brown_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"botania:livingwood_log"},{Count:64b,Slot:1b,id:"botania:livingwood_log"},{Count:64b,Slot:2b,id:"botania:livingwood_log"},{Count:64b,Slot:3b,id:"botania:livingwood_log"},{Count:64b,Slot:4b,id:"botania:livingwood_log"},{Count:64b,Slot:5b,id:"botania:livingwood_log"},{Count:64b,Slot:6b,id:"botania:livingwood_log"},{Count:64b,Slot:7b,id:"botania:livingwood_log"},{Count:64b,Slot:8b,id:"botania:livingwood_log"},{Count:64b,Slot:9b,id:"botania:livingwood_log"},{Count:64b,Slot:10b,id:"botania:livingwood_log"},{Count:64b,Slot:11b,id:"botania:livingwood_log"},{Count:64b,Slot:12b,id:"botania:livingwood_log"},{Count:64b,Slot:13b,id:"botania:livingwood_log"},{Count:64b,Slot:14b,id:"botania:livingwood_log"},{Count:64b,Slot:15b,id:"botania:livingwood_log"},{Count:64b,Slot:16b,id:"botania:livingwood_log"},{Count:64b,Slot:17b,id:"botania:livingwood_log"},{Count:64b,Slot:18b,id:"botania:livingwood_log"},{Count:64b,Slot:19b,id:"botania:livingwood_log"},{Count:64b,Slot:20b,id:"botania:livingwood_log"},{Count:64b,Slot:21b,id:"botania:livingwood_log"},{Count:64b,Slot:22b,id:"botania:livingwood_log"},{Count:64b,Slot:23b,id:"botania:livingwood_log"},{Count:64b,Slot:24b,id:"botania:livingwood_log"},{Count:64b,Slot:25b,id:"botania:livingwood_log"},{Count:64b,Slot:26b,id:"botania:livingwood_log"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_living_rock',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"botania:livingrock"},{Count:64b,Slot:1b,id:"botania:livingrock"},{Count:64b,Slot:2b,id:"botania:livingrock"},{Count:64b,Slot:3b,id:"botania:livingrock"},{Count:64b,Slot:4b,id:"botania:livingrock"},{Count:64b,Slot:5b,id:"botania:livingrock"},{Count:64b,Slot:6b,id:"botania:livingrock"},{Count:64b,Slot:7b,id:"botania:livingrock"},{Count:64b,Slot:8b,id:"botania:livingrock"},{Count:64b,Slot:9b,id:"botania:livingrock"},{Count:64b,Slot:10b,id:"botania:livingrock"},{Count:64b,Slot:11b,id:"botania:livingrock"},{Count:64b,Slot:12b,id:"botania:livingrock"},{Count:64b,Slot:13b,id:"botania:livingrock"},{Count:64b,Slot:14b,id:"botania:livingrock"},{Count:64b,Slot:15b,id:"botania:livingrock"},{Count:64b,Slot:16b,id:"botania:livingrock"},{Count:64b,Slot:17b,id:"botania:livingrock"},{Count:64b,Slot:18b,id:"botania:livingrock"},{Count:64b,Slot:19b,id:"botania:livingrock"},{Count:64b,Slot:20b,id:"botania:livingrock"},{Count:64b,Slot:21b,id:"botania:livingrock"},{Count:64b,Slot:22b,id:"botania:livingrock"},{Count:64b,Slot:23b,id:"botania:livingrock"},{Count:64b,Slot:24b,id:"botania:livingrock"},{Count:64b,Slot:25b,id:"botania:livingrock"},{Count:64b,Slot:26b,id:"botania:livingrock"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_enchanted_golden_apple',Item.of('minecraft:yellow_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:1b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:2b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:3b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:4b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:5b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:6b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:7b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:8b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:9b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:10b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:11b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:12b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:13b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:14b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:15b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:16b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:17b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:18b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:19b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:20b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:21b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:22b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:23b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:24b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:25b,id:"minecraft:enchanted_golden_apple"},{Count:64b,Slot:26b,id:"minecraft:enchanted_golden_apple"}],id:"minecraft:shulker_box"}}'))

    //
    singularity('kubejs:singularity_alloy_infused',Item.of('minecraft:red_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:alloy_infused"},{Count:64b,Slot:1b,id:"mekanism:alloy_infused"},{Count:64b,Slot:2b,id:"mekanism:alloy_infused"},{Count:64b,Slot:3b,id:"mekanism:alloy_infused"},{Count:64b,Slot:4b,id:"mekanism:alloy_infused"},{Count:64b,Slot:5b,id:"mekanism:alloy_infused"},{Count:64b,Slot:6b,id:"mekanism:alloy_infused"},{Count:64b,Slot:7b,id:"mekanism:alloy_infused"},{Count:64b,Slot:8b,id:"mekanism:alloy_infused"},{Count:64b,Slot:9b,id:"mekanism:alloy_infused"},{Count:64b,Slot:10b,id:"mekanism:alloy_infused"},{Count:64b,Slot:11b,id:"mekanism:alloy_infused"},{Count:64b,Slot:12b,id:"mekanism:alloy_infused"},{Count:64b,Slot:13b,id:"mekanism:alloy_infused"},{Count:64b,Slot:14b,id:"mekanism:alloy_infused"},{Count:64b,Slot:15b,id:"mekanism:alloy_infused"},{Count:64b,Slot:16b,id:"mekanism:alloy_infused"},{Count:64b,Slot:17b,id:"mekanism:alloy_infused"},{Count:64b,Slot:18b,id:"mekanism:alloy_infused"},{Count:64b,Slot:19b,id:"mekanism:alloy_infused"},{Count:64b,Slot:20b,id:"mekanism:alloy_infused"},{Count:64b,Slot:21b,id:"mekanism:alloy_infused"},{Count:64b,Slot:22b,id:"mekanism:alloy_infused"},{Count:64b,Slot:23b,id:"mekanism:alloy_infused"},{Count:64b,Slot:24b,id:"mekanism:alloy_infused"},{Count:64b,Slot:25b,id:"mekanism:alloy_infused"},{Count:64b,Slot:26b,id:"mekanism:alloy_infused"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_alloy_reinforced',Item.of('minecraft:light_blue_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:1b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:2b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:3b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:4b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:5b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:6b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:7b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:8b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:9b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:10b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:11b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:12b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:13b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:14b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:15b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:16b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:17b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:18b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:19b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:20b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:21b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:22b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:23b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:24b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:25b,id:"mekanism:alloy_reinforced"},{Count:64b,Slot:26b,id:"mekanism:alloy_reinforced"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_alloy_atomic',Item.of('minecraft:purple_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:1b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:2b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:3b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:4b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:5b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:6b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:7b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:8b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:9b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:10b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:11b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:12b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:13b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:14b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:15b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:16b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:17b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:18b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:19b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:20b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:21b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:22b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:23b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:24b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:25b,id:"mekanism:alloy_atomic"},{Count:64b,Slot:26b,id:"mekanism:alloy_atomic"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_plutonium',Item.of('minecraft:cyan_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:1b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:2b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:3b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:4b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:5b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:6b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:7b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:8b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:9b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:10b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:11b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:12b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:13b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:14b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:15b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:16b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:17b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:18b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:19b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:20b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:21b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:22b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:23b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:24b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:25b,id:"mekanism:pellet_plutonium"},{Count:64b,Slot:26b,id:"mekanism:pellet_plutonium"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_polonium',Item.of('minecraft:blue_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:1b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:2b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:3b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:4b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:5b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:6b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:7b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:8b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:9b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:10b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:11b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:12b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:13b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:14b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:15b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:16b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:17b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:18b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:19b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:20b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:21b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:22b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:23b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:24b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:25b,id:"mekanism:pellet_polonium"},{Count:64b,Slot:26b,id:"mekanism:pellet_polonium"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_hdpe',Item.of('minecraft:white_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:1b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:2b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:3b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:4b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:5b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:6b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:7b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:8b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:9b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:10b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:11b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:12b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:13b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:14b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:15b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:16b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:17b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:18b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:19b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:20b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:21b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:22b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:23b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:24b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:25b,id:"mekanism:hdpe_sheet"},{Count:64b,Slot:26b,id:"mekanism:hdpe_sheet"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_cuckoo',Item.of('minecraft:brown_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:cuckoo_clock"},{Count:64b,Slot:1b,id:"create:cuckoo_clock"},{Count:64b,Slot:2b,id:"create:cuckoo_clock"},{Count:64b,Slot:3b,id:"create:cuckoo_clock"},{Count:64b,Slot:4b,id:"create:cuckoo_clock"},{Count:64b,Slot:5b,id:"create:cuckoo_clock"},{Count:64b,Slot:6b,id:"create:cuckoo_clock"},{Count:64b,Slot:7b,id:"create:cuckoo_clock"},{Count:64b,Slot:8b,id:"create:cuckoo_clock"},{Count:64b,Slot:9b,id:"create:cuckoo_clock"},{Count:64b,Slot:10b,id:"create:cuckoo_clock"},{Count:64b,Slot:11b,id:"create:cuckoo_clock"},{Count:64b,Slot:12b,id:"create:cuckoo_clock"},{Count:64b,Slot:13b,id:"create:cuckoo_clock"},{Count:64b,Slot:14b,id:"create:cuckoo_clock"},{Count:64b,Slot:15b,id:"create:cuckoo_clock"},{Count:64b,Slot:16b,id:"create:cuckoo_clock"},{Count:64b,Slot:17b,id:"create:cuckoo_clock"},{Count:64b,Slot:18b,id:"create:cuckoo_clock"},{Count:64b,Slot:19b,id:"create:cuckoo_clock"},{Count:64b,Slot:20b,id:"create:cuckoo_clock"},{Count:64b,Slot:21b,id:"create:cuckoo_clock"},{Count:64b,Slot:22b,id:"create:cuckoo_clock"},{Count:64b,Slot:23b,id:"create:cuckoo_clock"},{Count:64b,Slot:24b,id:"create:cuckoo_clock"},{Count:64b,Slot:25b,id:"create:cuckoo_clock"},{Count:64b,Slot:26b,id:"create:cuckoo_clock"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_track',Item.of('minecraft:light_gray_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:track"},{Count:64b,Slot:1b,id:"create:track"},{Count:64b,Slot:2b,id:"create:track"},{Count:64b,Slot:3b,id:"create:track"},{Count:64b,Slot:4b,id:"create:track"},{Count:64b,Slot:5b,id:"create:track"},{Count:64b,Slot:6b,id:"create:track"},{Count:64b,Slot:7b,id:"create:track"},{Count:64b,Slot:8b,id:"create:track"},{Count:64b,Slot:9b,id:"create:track"},{Count:64b,Slot:10b,id:"create:track"},{Count:64b,Slot:11b,id:"create:track"},{Count:64b,Slot:12b,id:"create:track"},{Count:64b,Slot:13b,id:"create:track"},{Count:64b,Slot:14b,id:"create:track"},{Count:64b,Slot:15b,id:"create:track"},{Count:64b,Slot:16b,id:"create:track"},{Count:64b,Slot:17b,id:"create:track"},{Count:64b,Slot:18b,id:"create:track"},{Count:64b,Slot:19b,id:"create:track"},{Count:64b,Slot:20b,id:"create:track"},{Count:64b,Slot:21b,id:"create:track"},{Count:64b,Slot:22b,id:"create:track"},{Count:64b,Slot:23b,id:"create:track"},{Count:64b,Slot:24b,id:"create:track"},{Count:64b,Slot:25b,id:"create:track"},{Count:64b,Slot:26b,id:"create:track"}],id:"minecraft:shulker_box"}}'))
    
    singularity('kubejs:singularity_radiance',Item.of('minecraft:white_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:refined_radiance"},{Count:64b,Slot:1b,id:"create:refined_radiance"},{Count:64b,Slot:2b,id:"create:refined_radiance"},{Count:64b,Slot:3b,id:"create:refined_radiance"},{Count:64b,Slot:4b,id:"create:refined_radiance"},{Count:64b,Slot:5b,id:"create:refined_radiance"},{Count:64b,Slot:6b,id:"create:refined_radiance"},{Count:64b,Slot:7b,id:"create:refined_radiance"},{Count:64b,Slot:8b,id:"create:refined_radiance"},{Count:64b,Slot:9b,id:"create:refined_radiance"},{Count:64b,Slot:10b,id:"create:refined_radiance"},{Count:64b,Slot:11b,id:"create:refined_radiance"},{Count:64b,Slot:12b,id:"create:refined_radiance"},{Count:64b,Slot:13b,id:"create:refined_radiance"},{Count:64b,Slot:14b,id:"create:refined_radiance"},{Count:64b,Slot:15b,id:"create:refined_radiance"},{Count:64b,Slot:16b,id:"create:refined_radiance"},{Count:64b,Slot:17b,id:"create:refined_radiance"},{Count:64b,Slot:18b,id:"create:refined_radiance"},{Count:64b,Slot:19b,id:"create:refined_radiance"},{Count:64b,Slot:20b,id:"create:refined_radiance"},{Count:64b,Slot:21b,id:"create:refined_radiance"},{Count:64b,Slot:22b,id:"create:refined_radiance"},{Count:64b,Slot:23b,id:"create:refined_radiance"},{Count:64b,Slot:24b,id:"create:refined_radiance"},{Count:64b,Slot:25b,id:"create:refined_radiance"},{Count:64b,Slot:26b,id:"create:refined_radiance"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_shadow',Item.of('minecraft:black_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"create:shadow_steel"},{Count:64b,Slot:1b,id:"create:shadow_steel"},{Count:64b,Slot:2b,id:"create:shadow_steel"},{Count:64b,Slot:3b,id:"create:shadow_steel"},{Count:64b,Slot:4b,id:"create:shadow_steel"},{Count:64b,Slot:5b,id:"create:shadow_steel"},{Count:64b,Slot:6b,id:"create:shadow_steel"},{Count:64b,Slot:7b,id:"create:shadow_steel"},{Count:64b,Slot:8b,id:"create:shadow_steel"},{Count:64b,Slot:9b,id:"create:shadow_steel"},{Count:64b,Slot:10b,id:"create:shadow_steel"},{Count:64b,Slot:11b,id:"create:shadow_steel"},{Count:64b,Slot:12b,id:"create:shadow_steel"},{Count:64b,Slot:13b,id:"create:shadow_steel"},{Count:64b,Slot:14b,id:"create:shadow_steel"},{Count:64b,Slot:15b,id:"create:shadow_steel"},{Count:64b,Slot:16b,id:"create:shadow_steel"},{Count:64b,Slot:17b,id:"create:shadow_steel"},{Count:64b,Slot:18b,id:"create:shadow_steel"},{Count:64b,Slot:19b,id:"create:shadow_steel"},{Count:64b,Slot:20b,id:"create:shadow_steel"},{Count:64b,Slot:21b,id:"create:shadow_steel"},{Count:64b,Slot:22b,id:"create:shadow_steel"},{Count:64b,Slot:23b,id:"create:shadow_steel"},{Count:64b,Slot:24b,id:"create:shadow_steel"},{Count:64b,Slot:25b,id:"create:shadow_steel"},{Count:64b,Slot:26b,id:"create:shadow_steel"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_nether_air',Item.of('minecraft:red_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:1b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:2b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:3b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:4b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:5b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:6b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:7b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:8b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:9b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:10b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:11b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:12b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:13b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:14b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:15b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:16b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:17b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:18b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:19b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:20b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:21b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:22b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:23b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:24b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:25b,id:"kubejs:nether_air_bottle"},{Count:64b,Slot:26b,id:"kubejs:nether_air_bottle"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_end_air',Item.of('minecraft:black_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"botania:ender_air_bottle"},{Count:64b,Slot:1b,id:"botania:ender_air_bottle"},{Count:64b,Slot:2b,id:"botania:ender_air_bottle"},{Count:64b,Slot:3b,id:"botania:ender_air_bottle"},{Count:64b,Slot:4b,id:"botania:ender_air_bottle"},{Count:64b,Slot:5b,id:"botania:ender_air_bottle"},{Count:64b,Slot:6b,id:"botania:ender_air_bottle"},{Count:64b,Slot:7b,id:"botania:ender_air_bottle"},{Count:64b,Slot:8b,id:"botania:ender_air_bottle"},{Count:64b,Slot:9b,id:"botania:ender_air_bottle"},{Count:64b,Slot:10b,id:"botania:ender_air_bottle"},{Count:64b,Slot:11b,id:"botania:ender_air_bottle"},{Count:64b,Slot:12b,id:"botania:ender_air_bottle"},{Count:64b,Slot:13b,id:"botania:ender_air_bottle"},{Count:64b,Slot:14b,id:"botania:ender_air_bottle"},{Count:64b,Slot:15b,id:"botania:ender_air_bottle"},{Count:64b,Slot:16b,id:"botania:ender_air_bottle"},{Count:64b,Slot:17b,id:"botania:ender_air_bottle"},{Count:64b,Slot:18b,id:"botania:ender_air_bottle"},{Count:64b,Slot:19b,id:"botania:ender_air_bottle"},{Count:64b,Slot:20b,id:"botania:ender_air_bottle"},{Count:64b,Slot:21b,id:"botania:ender_air_bottle"},{Count:64b,Slot:22b,id:"botania:ender_air_bottle"},{Count:64b,Slot:23b,id:"botania:ender_air_bottle"},{Count:64b,Slot:24b,id:"botania:ender_air_bottle"},{Count:64b,Slot:25b,id:"botania:ender_air_bottle"},{Count:64b,Slot:26b,id:"botania:ender_air_bottle"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_blizz',Item.of('minecraft:light_blue_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"thermal:blizz_rod"},{Count:64b,Slot:1b,id:"thermal:blizz_rod"},{Count:64b,Slot:2b,id:"thermal:blizz_rod"},{Count:64b,Slot:3b,id:"thermal:blizz_rod"},{Count:64b,Slot:4b,id:"thermal:blizz_rod"},{Count:64b,Slot:5b,id:"thermal:blizz_rod"},{Count:64b,Slot:6b,id:"thermal:blizz_rod"},{Count:64b,Slot:7b,id:"thermal:blizz_rod"},{Count:64b,Slot:8b,id:"thermal:blizz_rod"},{Count:64b,Slot:9b,id:"thermal:blizz_rod"},{Count:64b,Slot:10b,id:"thermal:blizz_rod"},{Count:64b,Slot:11b,id:"thermal:blizz_rod"},{Count:64b,Slot:12b,id:"thermal:blizz_rod"},{Count:64b,Slot:13b,id:"thermal:blizz_rod"},{Count:64b,Slot:14b,id:"thermal:blizz_rod"},{Count:64b,Slot:15b,id:"thermal:blizz_rod"},{Count:64b,Slot:16b,id:"thermal:blizz_rod"},{Count:64b,Slot:17b,id:"thermal:blizz_rod"},{Count:64b,Slot:18b,id:"thermal:blizz_rod"},{Count:64b,Slot:19b,id:"thermal:blizz_rod"},{Count:64b,Slot:20b,id:"thermal:blizz_rod"},{Count:64b,Slot:21b,id:"thermal:blizz_rod"},{Count:64b,Slot:22b,id:"thermal:blizz_rod"},{Count:64b,Slot:23b,id:"thermal:blizz_rod"},{Count:64b,Slot:24b,id:"thermal:blizz_rod"},{Count:64b,Slot:25b,id:"thermal:blizz_rod"},{Count:64b,Slot:26b,id:"thermal:blizz_rod"}],id:"minecraft:shulker_box"}}'))

    singularity('kubejs:singularity_gem_obsidian',Item.of('minecraft:magenta_shulker_box', '{BlockEntityTag:{Items:[{Count:64b,Slot:0b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:1b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:2b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:3b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:4b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:5b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:6b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:7b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:8b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:9b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:10b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:11b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:12b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:13b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:14b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:15b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:16b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:17b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:18b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:19b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:20b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:21b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:22b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:23b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:24b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:25b,id:"cyclic:gem_obsidian"},{Count:64b,Slot:26b,id:"cyclic:gem_obsidian"}],id:"minecraft:shulker_box"}}'))

    //终极奇点
    mechanical_crafting('16x kubejs:ultimate_singularity',[
        'aaaaaaaaa',
        'abcdefgha',
        'aijklmnoa',
        'apqrstuva',
        'awxyzABCa',
        'aDEFGHIJa',
        'aKLMNOPQa',
        'aRSTUVWXa',
        'aaaaaaaaa'
    ],{
        a:'botania:gaia_ingot',
        b:'kubejs:singularity_mana',
        c:'kubejs:singularity_iron',
        d:'kubejs:singularity_copper',
        e:'kubejs:singularity_gold',
        f:'kubejs:singularity_netherite',
        g:'kubejs:singularity_nether_star',
        h:'kubejs:singularity_signalum',
        i:'kubejs:singularity_lumium',
        j:'kubejs:singularity_enderium',
        k:'kubejs:singularity_tin',
        l:'kubejs:singularity_lead',
        m:'kubejs:singularity_silver',
        n:'kubejs:singularity_bronze',
        o:'kubejs:singularity_electrum',
        p:'kubejs:singularity_invar',
        q:'kubejs:singularity_constantan',
        r:'kubejs:singularity_aluminum',
        s:'kubejs:singularity_purpur',
        t:'kubejs:singularity_refined_obsidian',
        u:'kubejs:singularity_refined_glowstone',
        v:'kubejs:singularity_osmium',
        w:'kubejs:singularity_andeside_alloy',
        x:'kubejs:singularity_zinc',
        y:'kubejs:singularity_brass',
        z:'kubejs:singularity_compositesteel',
        A:'kubejs:singularity_fluix',
        B:'kubejs:singularity_lapis',
        C:'kubejs:singularity_singularity',
        D:'kubejs:singularity_silicon',
        E:'kubejs:singularity_wool',
        F:'kubejs:singularity_blaze',
        G:'kubejs:singularity_mycelium',
        H:'kubejs:singularity_living_wood',
        I:'kubejs:singularity_living_rock',
        J:'kubejs:singularity_enchanted_golden_apple',
        K:'kubejs:singularity_alloy_infused',
        L:'kubejs:singularity_alloy_reinforced',
        M:'kubejs:singularity_alloy_atomic',
        N:'kubejs:singularity_plutonium',
        O:'kubejs:singularity_polonium',
        P:'kubejs:singularity_hdpe',
        Q:'kubejs:singularity_cuckoo',
        R:'kubejs:singularity_track',
        S:'kubejs:singularity_radiance',
        T:'kubejs:singularity_shadow',
        U:'kubejs:singularity_nether_air',
        V:'kubejs:singularity_end_air',
        W:'kubejs:singularity_blizz',
        X:'kubejs:singularity_gem_obsidian'
    }).id('singularity:mechanical_crafting/ultimate_singularity')
})