Ponder.registry(event => {
    event.create('kubejs:deepore_gen')
        .scene('deepore_gen',"Working Principle of Deep Ore Generator",(scene,util) =>{
            scene.showStructure()
            scene.idle(10)
            scene.text(50,"§by<0 §7, place machine",[2.5,1.5,2.5])
            scene.world.setBlock([2,1,2],'kubejs:deeporegen',false)
            scene.idle(60)
            scene.addKeyframe()
            scene.text(50,"§7Add §dwater§7, §dlava§7, §dmana§7 into §7machine",[2.5,1.5,2.5])
            scene.idle(60)
            scene.addKeyframe()
            scene.text(50,"§7Place §dDeepslate§7 on the machine",[2.5,2.5,2.5])
            scene.world.setBlock([2,2,2],'minecraft:deepslate',false)
            scene.idle(60)
            scene.addKeyframe()
            scene.text(50,"§7Wait a moment, ores will replace §7the §ddeepslate",[2.5,2.5,2.5])
            scene.world.setBlock([2,2,2],'thermal:deepslate_cinnabar_ore',true)
            scene.idle(60)
        })
})